"""created characters

Revision ID: b2680a7fa660
Revises: d267ab160a5c
Create Date: 2023-04-17 15:51:16.244562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2680a7fa660'
down_revision = 'd267ab160a5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('armor_id', sa.Integer(), nullable=True),
    sa.Column('weapon_id', sa.Integer(), nullable=True),
    sa.Column('specialty_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('health', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['armor_id'], ['armors.id'], name=op.f('fk_characters_armor_id_armors')),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], name=op.f('fk_characters_specialty_id_specialties')),
    sa.ForeignKeyConstraint(['weapon_id'], ['weapons.id'], name=op.f('fk_characters_weapon_id_weapons')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
